server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/task-manager
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true